# Generated by Django 3.2.22 on 2024-05-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='is_active',
            field=models.BooleanField(default='waiting'),
        ),
    ]
