# Generated by Django 4.1.1 on 2025-03-02 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_userregistration_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wake_freshness', models.CharField(max_length=10)),
                ('wake_frequency', models.CharField(max_length=10)),
                ('stress_level', models.CharField(max_length=10)),
                ('stress_management', models.CharField(max_length=50)),
                ('exercise_frequency', models.CharField(max_length=10)),
                ('weight_change', models.CharField(max_length=10)),
                ('device_usage', models.CharField(max_length=10)),
                ('caffeine_alcohol', models.CharField(max_length=10)),
                ('concentration', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
